gravitee-io/gravitee-repository

- src/main/java/io/gravitee/repository/management/api/EventRepository.java
- src/main/java/io/gravitee/repository/management/model/Event.java
- src/main/java/io/gravitee/repository/management/model/EventType.java
Unable to manually deploy API via Events.
> Features/event : Manually deploy API to the Gateway

- src/main/java/io/gravitee/repository/management/api/EventRepository.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Event.java
Add properties to event model.
Useful to search events by api_id to get history deployments.
Useful to remove api events.
> Enhance event with properties

- src/main/java/io/gravitee/repository/management/model/Api.java
> Associate a logo / a picture to an API

- src/main/java/io/gravitee/repository/management/model/Page.java
- src/main/java/io/gravitee/repository/management/model/PageSource.java
> feat(page): allow pages to be fetched from external resources

- src/main/java/io/gravitee/repository/analytics/api/AnalyticsRepository.java
- src/main/java/io/gravitee/repository/analytics/query/response/HitsResponse.java
- src/main/java/io/gravitee/repository/analytics/query/response/TopHitsResponse.java
This closes gravitee-io/issues#61
> feat(analytics): add global and top hits services

- src/main/java/io/gravitee/repository/management/model/User.java
> feat(security): Improve permission management

- pom.xml
- src/main/java/io/gravitee/repository/analytics/api/AnalyticsRepository.java
- src/main/java/io/gravitee/repository/management/api/EventRepository.java
This closes gravitee-io/issues#113
> feat(events): add search events method and add sort functionality for top hits analytics

- src/main/java/io/gravitee/repository/management/api/EventRepository.java
- src/main/java/io/gravitee/repository/management/api/search/EventCriteria.java
- src/main/java/io/gravitee/repository/management/api/search/Pageable.java
- src/main/java/io/gravitee/repository/management/api/search/builder/PageableBuilder.java
- src/main/java/io/gravitee/repository/management/api/search/builder/PageableImpl.java
> feat(repository): Preserve a single method to search for events.

- src/main/java/io/gravitee/repository/management/api/ViewRepository.java
- src/main/java/io/gravitee/repository/management/model/View.java
This closes https://github.com/gravitee-io/issues/issues/112
> Allows to group list of APIs by views

- pom.xml
- src/main/java/io/gravitee/repository/management/api/ApiRepository.java
- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/api/MembershipRepository.java
- src/main/java/io/gravitee/repository/management/api/UserRepository.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Membership.java
- src/main/java/io/gravitee/repository/management/model/MembershipReferenceType.java
> feat(membership): store memberships in a dedicated repository

- src/main/java/io/gravitee/repository/management/api/ApiRepository.java
- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/api/GroupRepository.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Group.java
> feat(group): manage group permissions

- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
> feat(subscription): api publisher could add app subscription

- src/main/java/io/gravitee/repository/management/api/TagRepository.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Tag.java
This closes https://github.com/gravitee-io/issues/issues/318
> Allows to CRUD sharding tags

- src/main/java/io/gravitee/repository/management/api/TenantRepository.java
- src/main/java/io/gravitee/repository/management/model/Tenant.java
> feat(gateway): Multi-tenant support

- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/ApplicationStatus.java
> fix(application): archive an application

- src/main/java/io/gravitee/repository/management/model/Api.java
This closes https://github.com/gravitee-io/issues/issues/500
> Apis with same name are filtered on hashed collections

- src/main/java/io/gravitee/repository/management/api/PageRepository.java
- src/main/java/io/gravitee/repository/management/model/Page.java
> feat(pages): set a page as an api homepage

- src/main/java/io/gravitee/repository/management/api/PageRepository.java
> feat(pages): add portal pages

- src/main/java/io/gravitee/repository/analytics/query/tabular/TabularQuery.java
- src/main/java/io/gravitee/repository/analytics/query/tabular/TabularQueryBuilder.java
- src/main/java/io/gravitee/repository/analytics/query/tabular/TabularResponse.java
- src/main/java/io/gravitee/repository/log/api/LogRepository.java
- src/main/java/io/gravitee/repository/log/model/Request.java
> feat(log): Request /response analysis

- src/main/java/io/gravitee/repository/management/api/MetadataRepository.java
- src/main/java/io/gravitee/repository/management/model/Metadata.java
- src/main/java/io/gravitee/repository/management/model/MetadataFormat.java
- src/main/java/io/gravitee/repository/management/model/MetadataReferenceType.java
> Add management of metadatas

- src/main/java/io/gravitee/repository/management/model/Api.java
> feat(api): Associate labels

- src/main/java/io/gravitee/repository/log/model/Request.java
> feat(log): Add a message settled by the gateway in case of error

- src/main/java/io/gravitee/repository/log/model/Request.java
> feat(log): Add gateway identifier

- pom.xml
- src/main/java/io/gravitee/repository/management/api/MembershipRepository.java
- src/main/java/io/gravitee/repository/management/api/RoleRepository.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Membership.java
- src/main/java/io/gravitee/repository/management/model/MembershipDefaultReferenceId.java
- src/main/java/io/gravitee/repository/management/model/Role.java
- src/main/java/io/gravitee/repository/management/model/RoleScope.java
- src/main/java/io/gravitee/repository/management/model/User.java
> feat(roles): implementation of custom roles

- src/main/java/io/gravitee/repository/management/model/Subscription.java
> Better management of closing plan : set a closed date on subscriptions and send a clearer email to all subscribers of the plan

- src/main/java/io/gravitee/repository/management/api/GroupRepository.java
- src/main/java/io/gravitee/repository/management/api/MembershipRepository.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Group.java
- src/main/java/io/gravitee/repository/management/model/Membership.java
- src/main/java/io/gravitee/repository/management/model/MembershipReferenceType.java
> feat(groups): move api/app groups to user groups

- src/main/java/io/gravitee/repository/healthcheck/api/HealthCheckRepository.java
- src/main/java/io/gravitee/repository/healthcheck/query/AbstractQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/AbstractQueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/Bucket.java
- src/main/java/io/gravitee/repository/healthcheck/query/FieldBucket.java
- src/main/java/io/gravitee/repository/healthcheck/query/Query.java
- src/main/java/io/gravitee/repository/healthcheck/query/QueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/QueryBuilders.java
- src/main/java/io/gravitee/repository/healthcheck/query/QueryFilter.java
- src/main/java/io/gravitee/repository/healthcheck/query/Response.java
- src/main/java/io/gravitee/repository/healthcheck/query/RootFilter.java
- src/main/java/io/gravitee/repository/healthcheck/query/availability/AvailabilityQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/availability/AvailabilityQueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/availability/AvailabilityResponse.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/Log.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsQueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsResponse.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/Step.java
- src/main/java/io/gravitee/repository/healthcheck/query/responsetime/AverageResponseTimeQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/responsetime/AverageResponseTimeQueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/responsetime/AverageResponseTimeResponse.java
> feat(healthcheck): Refactor health-check service for API's endpoints

- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Page.java
- src/main/java/io/gravitee/repository/management/model/Plan.java
>  feat(groups): restrict pages and documentation to a set of groups

- src/main/java/io/gravitee/repository/healthcheck/query/log/ExtendedLog.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/Request.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/Response.java
> feat(healthcheck): Store more information in case of HC fail

- src/main/java/io/gravitee/repository/management/api/ApiKeyRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApiKeyCriteria.java
> feat(apikey): New method for api-key refresh improvements

- pom.xml
- src/main/java/io/gravitee/repository/log/model/Log.java
> refactor(reporter): Log and metrics reporting

- src/main/java/io/gravitee/repository/management/api/RatingAnswerRepository.java
- src/main/java/io/gravitee/repository/management/api/RatingRepository.java
- src/main/java/io/gravitee/repository/management/model/Rating.java
- src/main/java/io/gravitee/repository/management/model/RatingAnswer.java
This closes gravitee-io/issues#840
> Implementation of rating of APIs

- pom.xml
- src/main/java/io/gravitee/repository/management/api/AuditRepository.java
- src/main/java/io/gravitee/repository/management/api/search/AuditCriteria.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/ApiKey.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
- src/main/java/io/gravitee/repository/management/model/Group.java
- src/main/java/io/gravitee/repository/management/model/Membership.java
- src/main/java/io/gravitee/repository/management/model/Metadata.java
- src/main/java/io/gravitee/repository/management/model/Page.java
- src/main/java/io/gravitee/repository/management/model/Plan.java
- src/main/java/io/gravitee/repository/management/model/Rating.java
- src/main/java/io/gravitee/repository/management/model/RatingAnswer.java
- src/main/java/io/gravitee/repository/management/model/Role.java
- src/main/java/io/gravitee/repository/management/model/Subscription.java
- src/main/java/io/gravitee/repository/management/model/Tag.java
- src/main/java/io/gravitee/repository/management/model/Tenant.java
- src/main/java/io/gravitee/repository/management/model/User.java
- src/main/java/io/gravitee/repository/management/model/View.java
> feat(audit): first implementation

- src/main/java/io/gravitee/repository/management/api/ViewRepository.java
- src/main/java/io/gravitee/repository/management/model/View.java
> feat(views): make views sortable, hidden and choose the default one

- src/main/java/io/gravitee/repository/healthcheck/query/AbstractQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/AbstractQueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/DateHistogramQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/DateHistogramQueryBuilder.java
- src/main/java/io/gravitee/repository/healthcheck/query/QueryBuilders.java
- src/main/java/io/gravitee/repository/healthcheck/query/response/histogram/DateHistogramResponse.java
This closes gravitee-io/issues#889
> feat: Added a chart to display global Health Check average

- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/api/SubscriptionRepository.java
- src/main/java/io/gravitee/repository/management/api/search/SubscriptionCriteria.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Plan.java
- src/main/java/io/gravitee/repository/management/model/Subscription.java
> feat(oauth2): Manage OAuth2 and JWT plan security type

- src/main/java/io/gravitee/repository/management/api/ParameterRepository.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
- src/main/java/io/gravitee/repository/management/model/Parameter.java
This closes gravitee-io/issues#932
> feat: allows to configure top APIs displayed on portal

- src/main/java/io/gravitee/repository/management/api/GenericNotificationConfigRepository.java
- src/main/java/io/gravitee/repository/management/api/PortalNotificationConfigRepository.java
- src/main/java/io/gravitee/repository/management/api/PortalNotificationRepository.java
- src/main/java/io/gravitee/repository/management/model/GenericNotificationConfig.java
- src/main/java/io/gravitee/repository/management/model/NotificationReferenceType.java
- src/main/java/io/gravitee/repository/management/model/PortalNotification.java
- src/main/java/io/gravitee/repository/management/model/PortalNotificationConfig.java
- src/main/java/io/gravitee/repository/management/model/PortalNotificationDefaultReferenceId.java
> feat(notifications): add user notifications

- src/main/java/io/gravitee/repository/management/model/User.java
This closes gravitee-io/issues#1073
> test: added some tests on sorted page results

- pom.xml
- src/main/java/io/gravitee/repository/management/model/Subscription.java
> feat(subscription): add a reason on accept and on request

- src/main/java/io/gravitee/repository/management/model/Group.java
- src/main/java/io/gravitee/repository/management/model/RoleScope.java
> feat(group): Delegate the management of a group

- src/main/java/io/gravitee/repository/management/model/User.java
This closes gravitee-io/issues#1230
> feat: Allows to reset a password of an internal user

- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsQueryBuilder.java
This closes gravitee-io/issues#1240
> feat: allows to display HC status transitions

- src/main/java/io/gravitee/repository/management/model/View.java
Closes gravitee-io/issues#1011
> feat(view): add highlight API

- src/main/java/io/gravitee/repository/management/api/ApiRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApiCriteria.java
- src/main/java/io/gravitee/repository/management/api/search/ApiFieldExclusionFilter.java
This closes gravitee-io/issues#561
> feat: Allows to search and filter APIs

- pom.xml
- src/main/java/io/gravitee/repository/log/api/LogRepository.java
closes gravitee-io/issues#1412
> feat(log): add log timestamp to select elasticsearch indices

- src/main/java/io/gravitee/repository/management/api/DictionaryRepository.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
- src/main/java/io/gravitee/repository/management/model/Dictionary.java
- src/main/java/io/gravitee/repository/management/model/DictionaryProvider.java
- src/main/java/io/gravitee/repository/management/model/DictionaryTrigger.java
- src/main/java/io/gravitee/repository/management/model/DictionaryType.java
- src/main/java/io/gravitee/repository/management/model/Event.java
Closes gravitee-io/issues#1400
> feat(dictionary): Add global dictionary

- src/main/java/io/gravitee/repository/log/model/Log.java
Closes gravitee-io/issues#1536
> feat(analytics): Add Host HTTP header into analytics

- src/main/java/io/gravitee/repository/management/api/ApiHeaderRepository.java
- src/main/java/io/gravitee/repository/management/model/ApiHeader.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
> feat(api-portal-header): edit headers

- src/main/java/io/gravitee/repository/management/model/GenericNotificationConfig.java
> feat(proxy): add global proxy

- src/main/java/io/gravitee/repository/management/model/ApiHeader.java
- src/main/java/io/gravitee/repository/media/api/MediaRepository.java
- src/main/java/io/gravitee/repository/media/model/Media.java
> feat(portal): Allows to persist images to use it on documentation pages

- src/main/java/io/gravitee/repository/management/api/AlertRepository.java
- src/main/java/io/gravitee/repository/management/model/Alert.java
- src/main/java/io/gravitee/repository/management/model/AlertCondition.java
This closes gravitee-io/issues#63
> feat: allows to send an alert when the HC status changes

- src/main/java/io/gravitee/repository/management/model/Api.java
Closes gravitee-io/issues#1658
> feat(audit): Add event for API rollback

- src/main/java/io/gravitee/repository/management/model/Plan.java
Closes gravitee-io/issues#1762
> feat(plan): A plan can be depreciate to close subscriptions

- src/main/java/io/gravitee/repository/management/model/ApiKey.java
- src/main/java/io/gravitee/repository/management/model/Subscription.java
Closes gravitee-io/issues#1753
> feat(souscription): A subscription can be paused and resumed

- src/main/java/io/gravitee/repository/management/api/PageRepository.java
- src/main/java/io/gravitee/repository/management/api/search/PageCriteria.java
> feat(pages): redesign management + multi subfolder

- src/main/java/io/gravitee/repository/management/model/Page.java
This closes gravitee-io/issues#1825
> fix: Add a link to the git repository defined on a documentation page

- src/main/java/io/gravitee/repository/management/model/View.java
closes gravitee-io/issues#1821
> feat(view): add picture to a portal view

- src/main/java/io/gravitee/repository/management/model/Plan.java
> fix(plan) do not redeploy api on every plan modification

- src/main/java/io/gravitee/repository/management/api/InvitationRepository.java
- src/main/java/io/gravitee/repository/management/model/Group.java
- src/main/java/io/gravitee/repository/management/model/Invitation.java
- src/main/java/io/gravitee/repository/management/model/InvitationReferenceType.java
This closes gravitee-io/issues#1818
> feat: Invite a user in a group

- src/main/java/io/gravitee/repository/management/model/PageType.java
> feat(tree): fetch pages recursively

- src/main/java/io/gravitee/repository/log/model/Log.java
This closes gravitee-io/issues#1948
> feat: Audit on API user from JWT

- src/main/java/io/gravitee/repository/management/model/Event.java
This closes gravitee-io/issues#2067
> feat: Optimizing event recuperation

- src/main/java/io/gravitee/repository/management/api/UserRepository.java
- src/main/java/io/gravitee/repository/management/api/search/UserCriteria.java
- src/main/java/io/gravitee/repository/management/model/User.java
- src/main/java/io/gravitee/repository/management/model/UserStatus.java
> feat(user): archive users

- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/ApiKey.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
- src/main/java/io/gravitee/repository/management/model/Dictionary.java
- src/main/java/io/gravitee/repository/management/model/Membership.java
- src/main/java/io/gravitee/repository/management/model/Metadata.java
- src/main/java/io/gravitee/repository/management/model/Page.java
- src/main/java/io/gravitee/repository/management/model/Plan.java
- src/main/java/io/gravitee/repository/management/model/Rating.java
- src/main/java/io/gravitee/repository/management/model/RatingAnswer.java
- src/main/java/io/gravitee/repository/management/model/Subscription.java
> fix(audit): add missing events

- src/main/java/io/gravitee/repository/management/model/Api.java
closes gravitee-io/issues#2103
> feat(audit): add API Logging configuration audit logs

- src/main/java/io/gravitee/repository/management/model/Tag.java
This closes gravitee-io/issues#1995
> feat: Allows to define permission to publish on a sharding tag

- src/main/java/io/gravitee/repository/management/api/CommandRepository.java
- src/main/java/io/gravitee/repository/management/api/search/CommandCriteria.java
- src/main/java/io/gravitee/repository/management/model/Command.java
- src/main/java/io/gravitee/repository/management/model/MessageRecipient.java
> feat(search): synchronize search indexes across management instances

- src/main/java/io/gravitee/repository/management/model/ClientRegistrationProvider.java
Closes gravitee-io/issues#2207
> feat(dcr): Support multiple initial access token providers

- src/main/java/io/gravitee/repository/management/model/IdentityProvider.java
refactoring from 1.20.16 due to new idp management
fix gravitee-io/issues#2124
> feat(idp): oauth idp could authorize users without email

- src/main/java/io/gravitee/repository/management/api/WorkflowRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApiCriteria.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/ApiLifecycleState.java
- src/main/java/io/gravitee/repository/management/model/Workflow.java
This closes gravitee-io/issues#1996
> feat: lifecycle API and review workflow

- src/main/java/io/gravitee/repository/log/model/Log.java
This closes gravitee-io/issues#1997
> feat: Multi analytics dashboards

- src/main/java/io/gravitee/repository/management/model/Plan.java
Closes gravitee-io/issues#2219
> feat(plan): Manage plan deployment using sharding tags

- src/main/java/io/gravitee/repository/management/model/ClientRegistrationProvider.java
Closes gravitee-io/issues#2350
> feat(application): Add renew client_secret support

- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsQuery.java
- src/main/java/io/gravitee/repository/healthcheck/query/log/LogsQueryBuilder.java
closes gravitee-io/issues#2378
> feat(healthcheck): adding a time filter in the healthcheck screen

- src/main/java/io/gravitee/repository/management/model/Application.java
Closes gravitee-io/issues#2288
> feat(env): add 'picture' management for Application

- pom.xml
- src/main/java/io/gravitee/repository/ratelimit/api/RateLimitRepository.java
- src/main/java/io/gravitee/repository/ratelimit/api/RateLimitService.java
- src/main/java/io/gravitee/repository/ratelimit/model/RateLimit.java
Closes gravitee-io/issues#2570
> Rx ratelimit

- src/main/java/io/gravitee/repository/ratelimit/api/RateLimitRepository.java
Closes gravitee-io/issues#2570
> feat(rate-limit): Reactive implementation

- src/main/java/io/gravitee/repository/management/api/GenericNotificationConfigRepository.java
- src/main/java/io/gravitee/repository/management/api/PortalNotificationConfigRepository.java
> fix(user): remove user notif on delete user

- src/main/java/io/gravitee/repository/management/api/PortalNotificationRepository.java
Closes gravitee-io/issues#2699
> feat(v3): add findById

- src/main/java/io/gravitee/repository/management/model/Api.java
> fix(audits): add api events

- src/main/java/io/gravitee/repository/management/api/MembershipRepository.java
- src/main/java/io/gravitee/repository/management/api/PortalNotificationConfigRepository.java
> fix(api): delete memberships and notifications on delete

- src/main/java/io/gravitee/repository/management/model/PageType.java
Closes gravitee-io/issues#3048
> feat(portal): Adding LINK and SYSTEM_FOLDER as new Page type

- src/main/java/io/gravitee/repository/management/api/OrganizationRepository.java
- src/main/java/io/gravitee/repository/management/api/RoleRepository.java
- src/main/java/io/gravitee/repository/management/api/UserRepository.java
- src/main/java/io/gravitee/repository/management/api/search/UserCriteria.java
- src/main/java/io/gravitee/repository/management/model/Organization.java
- src/main/java/io/gravitee/repository/management/model/User.java
- src/main/java/io/gravitee/repository/management/model/UserReferenceType.java
Closes gravitee-io/issues#3182
> feat(multi-env): add organization feature

- src/main/java/io/gravitee/repository/management/api/ThemeRepository.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
- src/main/java/io/gravitee/repository/management/model/Theme.java
- src/main/java/io/gravitee/repository/management/model/ThemeReferenceType.java
> feat: add theme repository

- src/main/java/io/gravitee/repository/management/api/AlertEventRepository.java
- src/main/java/io/gravitee/repository/management/api/search/AlertEventCriteria.java
- src/main/java/io/gravitee/repository/management/model/AlertEvent.java
Closes gravitee-io/issues#3185
> feat(alert): Add alert history

- src/main/java/io/gravitee/repository/management/api/ApiHeaderRepository.java
- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/api/DictionaryRepository.java
- src/main/java/io/gravitee/repository/management/api/EntrypointRepository.java
- src/main/java/io/gravitee/repository/management/api/EnvironmentRepository.java
- src/main/java/io/gravitee/repository/management/api/GroupRepository.java
- src/main/java/io/gravitee/repository/management/api/MembershipRepository.java
- src/main/java/io/gravitee/repository/management/api/RoleRepository.java
- src/main/java/io/gravitee/repository/management/api/UserRepository.java
- src/main/java/io/gravitee/repository/management/api/ViewRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApiCriteria.java
- src/main/java/io/gravitee/repository/management/api/search/CommandCriteria.java
- src/main/java/io/gravitee/repository/management/api/search/EventCriteria.java
- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/ApiHeader.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Command.java
- src/main/java/io/gravitee/repository/management/model/Dictionary.java
- src/main/java/io/gravitee/repository/management/model/Entrypoint.java
- src/main/java/io/gravitee/repository/management/model/Environment.java
- src/main/java/io/gravitee/repository/management/model/Event.java
- src/main/java/io/gravitee/repository/management/model/Group.java
- src/main/java/io/gravitee/repository/management/model/Membership.java
- src/main/java/io/gravitee/repository/management/model/MembershipMemberType.java
- src/main/java/io/gravitee/repository/management/model/MembershipReferenceType.java
- src/main/java/io/gravitee/repository/management/model/Role.java
- src/main/java/io/gravitee/repository/management/model/RoleScope.java
- src/main/java/io/gravitee/repository/management/model/View.java
Closes gravitee-io/issues#3206
> feat(multi-env): mix membership scopes MANAGEMENT & PORTAL

- src/main/java/io/gravitee/repository/management/model/User.java
> feat: Allow users to subscribe to newsletters

- src/main/java/io/gravitee/repository/management/model/View.java
Closes gravitee-io/issues#3767
> feat(management): remove Default view ALL and 'default' field

- src/main/java/io/gravitee/repository/management/model/AlertEventRule.java
- src/main/java/io/gravitee/repository/management/model/AlertEventType.java
- src/main/java/io/gravitee/repository/management/model/AlertTrigger.java
Closes gravitee-io/issues#3970
> feat(alert): Support for alert templates

- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Category.java
> feat: Allows to define a background on the APIs/Apps/Categories headers

- src/main/java/io/gravitee/repository/management/model/Api.java
- src/main/java/io/gravitee/repository/management/model/Application.java
- src/main/java/io/gravitee/repository/management/model/Group.java
Closes gravitee-io/issues#4134
> feat(management): add a "disableEmailNotification" option in groups, APIs and applications

- src/main/java/io/gravitee/repository/management/model/User.java
- src/main/java/io/gravitee/repository/management/model/UserStatus.java
Closes gravitee-io/issues#4069
> feat(registration): add 2 user status to manage user registration

- src/main/java/io/gravitee/repository/management/api/PageRevisionRepository.java
- src/main/java/io/gravitee/repository/management/model/PageRevision.java
> feat(management-api/reporter): #146 addition of page revision

- src/main/java/io/gravitee/repository/management/api/CategoryRepository.java
- src/main/java/io/gravitee/repository/management/model/Category.java
Closes gravitee-io/issues#4067
> feat(management): associate a page to a category

- src/main/java/io/gravitee/repository/management/api/PageRepository.java
- src/main/java/io/gravitee/repository/management/api/search/PageCriteria.java
- src/main/java/io/gravitee/repository/management/model/Page.java
Addition of findAll method on PageRepository
fix gravitee-io/issues#3196
> feat(management): auto fetch pages based on user configuration

- src/main/java/io/gravitee/repository/management/api/MetadataRepository.java
- src/main/java/io/gravitee/repository/management/api/search/PageCriteria.java
- src/main/java/io/gravitee/repository/media/api/MediaRepository.java
fix gravitee-io/issues#4149
fix gravitee-io/issues#3156
> fix(management): resolve API import/export

- src/main/java/io/gravitee/repository/management/model/ApiKey.java
Closes gravitee-io/issues#4227
> feat(apikey): allow apikey reactivation

- src/main/java/io/gravitee/repository/management/model/UserStatus.java
Closes gravitee-io/issues#4269
> feat(management): replace DISABLED by REJECTED

- src/main/java/io/gravitee/repository/management/model/Page.java
- src/main/java/io/gravitee/repository/management/model/PageMedia.java
- src/main/java/io/gravitee/repository/media/api/MediaRepository.java
Closes gravitee-io/issues#4066
> feat(management): add assets to pages

- src/main/java/io/gravitee/repository/management/model/Workflow.java
> feat(management): addition of workflow audit event

- src/main/java/io/gravitee/repository/management/model/User.java
> fix(mng): addition of User AuditEvent

- src/main/java/io/gravitee/repository/management/model/ApiKey.java
- src/main/java/io/gravitee/repository/management/model/Event.java
- src/main/java/io/gravitee/repository/management/model/Subscription.java
- src/main/java/io/gravitee/repository/ratelimit/model/RateLimit.java
Closes gravitee-io/issues#4493
> feat(cluster): Add clustering capabilities

- src/main/java/io/gravitee/repository/management/model/Audit.java
Closes gravitee-io/issues#3976
> feat(repository): replace audit PORTAL type with ENVIRONMENT and ORGANIZATION

- pom.xml
- src/main/java/io/gravitee/repository/management/api/NotificationTemplateRepository.java
- src/main/java/io/gravitee/repository/management/model/Audit.java
- src/main/java/io/gravitee/repository/management/model/NotificationTemplate.java
- src/main/java/io/gravitee/repository/management/model/NotificationTemplateReferenceType.java
- src/main/java/io/gravitee/repository/management/model/NotificationTemplateType.java
+ upgrade gravitee dependancies
Closes gravitee-io/issues#4297
> feat(notification): manage notif template in database

- src/main/java/io/gravitee/repository/management/api/TicketRepository.java
- src/main/java/io/gravitee/repository/management/api/search/Order.java
- src/main/java/io/gravitee/repository/management/api/search/Sortable.java
- src/main/java/io/gravitee/repository/management/api/search/TicketCriteria.java
- src/main/java/io/gravitee/repository/management/api/search/builder/SortableBuilder.java
- src/main/java/io/gravitee/repository/management/api/search/builder/SortableImpl.java
- src/main/java/io/gravitee/repository/management/model/Ticket.java
> feat: support tickets history

- src/main/java/io/gravitee/repository/management/api/ParameterRepository.java
- src/main/java/io/gravitee/repository/management/model/ParameterReferenceType.java
Closes gravitee-io/issues#4642
> feat(repository): manage Org & Env in parameters

- src/main/java/io/gravitee/repository/management/api/UserRepository.java
> feat(repository/user): addition of findByEmail

- src/main/java/io/gravitee/repository/management/model/DashboardReferenceType.java
Fixes https://github.com/gravitee-io/issues/issues/4747
> feat: console dashboard page

- src/main/java/io/gravitee/repository/management/model/Event.java
Fixes https://github.com/gravitee-io/issues/issues/4742
> feat: associate a label to an api deployment

- src/main/java/io/gravitee/repository/management/api/OrganizationRepository.java
- src/main/java/io/gravitee/repository/management/model/Environment.java
- src/main/java/io/gravitee/repository/management/model/Organization.java
Closes gravitee-io/issues#4287
> feat(cockpit): handle organization and environment commands

- src/main/java/io/gravitee/repository/management/api/InstallationRepository.java
- src/main/java/io/gravitee/repository/management/model/Installation.java
Closes gravitee-io/issues#4766
> feat(cockpit): manage cockpit installation registration

- src/main/java/io/gravitee/repository/management/model/Group.java
Closes gravitee-io/issues#5133
> feat(management): Manage API PO in a group

- src/main/java/io/gravitee/repository/management/api/search/PageCriteria.java
- src/main/java/io/gravitee/repository/management/model/Page.java
Fixes https://github.com/gravitee-io/issues/issues/4893
> feat: setting to make portal pages non-visible for anonymous user

- src/main/java/io/gravitee/repository/management/model/Theme.java
> feat(portal): allows to change favicon

- src/main/java/io/gravitee/repository/management/api/MembershipRepository.java
- src/main/java/io/gravitee/repository/management/api/OrganizationRepository.java
Closes gravitee-io/issues#5360
> Merge 3.6.2

- pom.xml
Closes gravitee-io/issues#5104
> feat(cockpit): Propagate monitoring data to cockpit

- src/main/java/io/gravitee/repository/management/model/AccessControl.java
- src/main/java/io/gravitee/repository/management/model/Page.java
> feat: add ACL on custom link

- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/model/Application.java
Fixes https://github.com/gravitee-io/issues/issues/4453
> feat: allow to restore an archived application

- src/main/java/io/gravitee/repository/management/api/EntrypointRepository.java
- src/main/java/io/gravitee/repository/management/api/GroupRepository.java
- src/main/java/io/gravitee/repository/management/api/TenantRepository.java
- src/main/java/io/gravitee/repository/management/model/Entrypoint.java
- src/main/java/io/gravitee/repository/management/model/EntrypointReferenceType.java
- src/main/java/io/gravitee/repository/management/model/Tag.java
- src/main/java/io/gravitee/repository/management/model/TagReferenceType.java
- src/main/java/io/gravitee/repository/management/model/Tenant.java
- src/main/java/io/gravitee/repository/management/model/TenantReferenceType.java
> feat: associate sharding tags and tenants to organization

- src/main/java/io/gravitee/repository/management/api/DictionaryRepository.java
- src/main/java/io/gravitee/repository/management/api/EnvironmentRepository.java
- src/main/java/io/gravitee/repository/management/api/OrganizationRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApiCriteria.java
- src/main/java/io/gravitee/repository/management/api/search/EventCriteria.java
- src/main/java/io/gravitee/repository/management/model/Event.java
Fixes https://github.com/gravitee-io/issues/issues/5357
> feat: allow to associate a gateway to environments

- src/main/java/io/gravitee/repository/management/api/search/ApiCriteria.java
Closes gravitee-io/issues#5298
> feat(management): allow to filter by context-path

- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApplicationCriteria.java
> fix: search only user authorized applications by name

- src/main/java/io/gravitee/repository/management/api/AlertTriggerRepository.java
- src/main/java/io/gravitee/repository/management/api/ApplicationRepository.java
- src/main/java/io/gravitee/repository/management/api/search/ApplicationCriteria.java
* search applications in many environments
* search alertTrigger for many references
Closes gravitee-io/issues#5341
> feat(management): allow to define consumer alerts

- src/main/java/io/gravitee/repository/management/api/FlowRepository.java
- src/main/java/io/gravitee/repository/management/model/Event.java
- src/main/java/io/gravitee/repository/management/model/Organization.java
- src/main/java/io/gravitee/repository/management/model/flow/Flow.java
- src/main/java/io/gravitee/repository/management/model/flow/FlowConsumer.java
- src/main/java/io/gravitee/repository/management/model/flow/FlowConsumerType.java
- src/main/java/io/gravitee/repository/management/model/flow/FlowOperator.java
- src/main/java/io/gravitee/repository/management/model/flow/FlowReferenceType.java
- src/main/java/io/gravitee/repository/management/model/flow/FlowStep.java
> feat(management): platform policies

- src/main/java/io/gravitee/repository/management/api/search/ApiKeyCriteria.java
**Issue**
https://github.com/gravitee-io/issues/issues/3887
> feat: add fields to filter by expiration date in ApiKeyCriteria

- src/main/java/io/gravitee/repository/management/model/ApiKey.java
- src/main/java/io/gravitee/repository/management/model/Subscription.java
**Issue**
https://github.com/gravitee-io/issues/issues/3887
> feat: add field to store info about the last pre expiration notif sent

- src/main/java/io/gravitee/repository/management/api/PromotionRepository.java
- src/main/java/io/gravitee/repository/management/model/Promotion.java
- src/main/java/io/gravitee/repository/management/model/PromotionStatus.java
**Issue**
https://github.com/gravitee-io/issues/issues/5526
**Description**
Create `Promotion`, `PromotionStatus` classes and `PromotionRepository` interface.
> Add Promotion repository and models

- src/main/java/io/gravitee/repository/management/model/Workflow.java
Closes gravitee-io/issues#5673
> fix(audit): add api-review events in audit event list

- src/main/java/io/gravitee/repository/management/api/PromotionRepository.java
- src/main/java/io/gravitee/repository/management/api/search/PromotionCriteria.java
- src/main/java/io/gravitee/repository/management/model/Promotion.java
- src/main/java/io/gravitee/repository/management/model/PromotionAuthor.java
**Issue**
https://github.com/gravitee-io/issues/issues/5527
**Description**
- add `PromotionCriteria` and a search method in `PromotionRepository`
- add source and target env names, author and apiId fields to `Promotion`
> Add search method in PromotionRepository and new fields in Promotion
